# 1. apply Init + Attr:
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --sample_peer_size 5 --sample_strategy cos-similarity  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Init+Attr --known 0.5 uci --train_edge 0.7 --data yacht
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --sample_peer_size 5 --sample_strategy cos-similarity  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Init+Attr --known 0.5 uci --train_edge 0.7 --data wine
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --sample_peer_size 5 --sample_strategy cos-similarity  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Init+Attr --known 0.5 uci --train_edge 0.7 --data housing
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --sample_peer_size 5 --sample_strategy cos-similarity  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Init+Attr --known 0.5 uci --train_edge 0.7 --data concrete
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --sample_peer_size 5 --sample_strategy cos-similarity  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Init+Attr --known 0.5 uci --train_edge 0.7 --data energy
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --sample_peer_size 5 --sample_strategy cos-similarity  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Init+Attr --known 0.5 uci --train_edge 0.7 --data power
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --sample_peer_size 5 --sample_strategy cos-similarity  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Init+Attr --known 0.5 uci --train_edge 0.7 --data kin8nm
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --sample_peer_size 5 --sample_strategy cos-similarity  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Init+Attr --known 0.5 uci --train_edge 0.7 --data naval


# 2. apply Init + Peer:
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Init+Peer --known 0.5 uci --train_edge 0.7 --data yacht
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Init+Peer --known 0.5 uci --train_edge 0.7 --data wine
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Init+Peer --known 0.5 uci --train_edge 0.7 --data housing
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Init+Peer --known 0.5 uci --train_edge 0.7 --data concrete
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Init+Peer --known 0.5 uci --train_edge 0.7 --data energy
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Init+Peer --known 0.5 uci --train_edge 0.7 --data power
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Init+Peer --known 0.5 uci --train_edge 0.7 --data kin8nm
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Init+Peer --known 0.5 uci --train_edge 0.7 --data naval

# 3. apply Random Sampling:
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Random_Sampling --known 0.5 uci --train_edge 0.7 --data yacht
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Random_Sampling --known 0.5 uci --train_edge 0.7 --data wine
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Random_Sampling --known 0.5 uci --train_edge 0.7 --data housing
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Random_Sampling --known 0.5 uci --train_edge 0.7 --data concrete
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Random_Sampling --known 0.5 uci --train_edge 0.7 --data energy
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Random_Sampling --known 0.5 uci --train_edge 0.7 --data power
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Random_Sampling --known 0.5 uci --train_edge 0.7 --data kin8nm
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/Random_Sampling --known 0.5 uci --train_edge 0.7 --data naval

# 4. Normal Masking:
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/normal_masking --masking_distribution normal --known 0.5 uci --train_edge 0.7 --data yacht
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/normal_masking --masking_distribution normal --known 0.5 uci --train_edge 0.7 --data wine
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/normal_masking --masking_distribution normal --known 0.5 uci --train_edge 0.7 --data housing
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/normal_masking --masking_distribution normal --known 0.5 uci --train_edge 0.7 --data concrete
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/normal_masking --masking_distribution normal --known 0.5 uci --train_edge 0.7 --data energy
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/normal_masking --masking_distribution normal --known 0.5 uci --train_edge 0.7 --data power
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/normal_masking --masking_distribution normal --known 0.5 uci --train_edge 0.7 --data kin8nm
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/normal_masking --masking_distribution normal --known 0.5 uci --train_edge 0.7 --data naval

# 5. Different Sample Peer Size:
# Peer = 1
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 1  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_1 --known 0.5 uci --train_edge 0.7 --data yacht
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 1  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_1 --known 0.5 uci --train_edge 0.7 --data wine
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 1  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_1 --known 0.5 uci --train_edge 0.7 --data housing
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 1  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_1 --known 0.5 uci --train_edge 0.7 --data concrete
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 1  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_1 --known 0.5 uci --train_edge 0.7 --data energy
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 1  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_1 --known 0.5 uci --train_edge 0.7 --data power
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 1  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_1 --known 0.5 uci --train_edge 0.7 --data kin8nm
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 1  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_1 --known 0.5 uci --train_edge 0.7 --data naval

# Peer = 2
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 2  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_2 --known 0.5 uci --train_edge 0.7 --data yacht
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 2  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_2 --known 0.5 uci --train_edge 0.7 --data wine
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 2  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_2 --known 0.5 uci --train_edge 0.7 --data housing
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 2  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_2 --known 0.5 uci --train_edge 0.7 --data concrete
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 2  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_2 --known 0.5 uci --train_edge 0.7 --data energy
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 2  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_2 --known 0.5 uci --train_edge 0.7 --data power
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 2  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_2 --known 0.5 uci --train_edge 0.7 --data kin8nm
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 2  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_2 --known 0.5 uci --train_edge 0.7 --data naval

# Peer = 5
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_5 --known 0.5 uci --train_edge 0.7 --data yacht
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_5 --known 0.5 uci --train_edge 0.7 --data wine
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_5 --known 0.5 uci --train_edge 0.7 --data housing
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_5 --known 0.5 uci --train_edge 0.7 --data concrete
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_5 --known 0.5 uci --train_edge 0.7 --data energy
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_5 --known 0.5 uci --train_edge 0.7 --data power
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_5 --known 0.5 uci --train_edge 0.7 --data kin8nm
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_5 --known 0.5 uci --train_edge 0.7 --data naval

# Peer = 15
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 15  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_15 --known 0.5 uci --train_edge 0.7 --data yacht
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 15  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_15 --known 0.5 uci --train_edge 0.7 --data wine
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 15  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_15 --known 0.5 uci --train_edge 0.7 --data housing
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 15  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_15 --known 0.5 uci --train_edge 0.7 --data concrete
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 15  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_15 --known 0.5 uci --train_edge 0.7 --data energy
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 15  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_15 --known 0.5 uci --train_edge 0.7 --data power
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 15  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_15 --known 0.5 uci --train_edge 0.7 --data kin8nm
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 15  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_15 --known 0.5 uci --train_edge 0.7 --data naval


# Peer = 20
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 20  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_20 --known 0.5 uci --train_edge 0.7 --data yacht
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 20  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_20 --known 0.5 uci --train_edge 0.7 --data wine
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 20  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_20 --known 0.5 uci --train_edge 0.7 --data housing
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 20  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_20 --known 0.5 uci --train_edge 0.7 --data concrete
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 20  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_20 --known 0.5 uci --train_edge 0.7 --data energy
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 20  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_20 --known 0.5 uci --train_edge 0.7 --data power
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 20  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_20 --known 0.5 uci --train_edge 0.7 --data kin8nm
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 20  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation/sample_peer_size_20 --known 0.5 uci --train_edge 0.7 --data naval


# 6. Different epsilon:
# epsilon = 0
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 0 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e0 --known 0.5 uci --train_edge 0.7 --data yacht
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 0 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e0 --known 0.5 uci --train_edge 0.7 --data wine
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 0 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e0 --known 0.5 uci --train_edge 0.7 --data housing
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 0 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e0 --known 0.5 uci --train_edge 0.7 --data concrete
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 0 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e0 --known 0.5 uci --train_edge 0.7 --data energy
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 0 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e0 --known 0.5 uci --train_edge 0.7 --data power
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 0 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e0 --known 0.5 uci --train_edge 0.7 --data kin8nm
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 0 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e0 --known 0.5 uci --train_edge 0.7 --data naval

# epsilon = 1e-5
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-5 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e1e5  --known 0.5 uci --train_edge 0.7 --data yacht
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-5 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e1e5  --known 0.5 uci --train_edge 0.7 --data wine
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-5 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e1e5  --known 0.5 uci --train_edge 0.7 --data housing
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-5 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e1e5  --known 0.5 uci --train_edge 0.7 --data concrete
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-5 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e1e5  --known 0.5 uci --train_edge 0.7 --data energy
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-5 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e1e5  --known 0.5 uci --train_edge 0.7 --data power
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-5 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e1e5  --known 0.5 uci --train_edge 0.7 --data kin8nm
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-5 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e1e5  --known 0.5 uci --train_edge 0.7 --data naval

# epsilon = 1e-3
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-3 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e1e3 --known 0.5 uci --train_edge 0.7 --data yacht
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-3 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e1e3 --known 0.5 uci --train_edge 0.7 --data wine
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-3 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e1e3 --known 0.5 uci --train_edge 0.7 --data housing
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-3 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e1e3 --known 0.5 uci --train_edge 0.7 --data concrete
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-3 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e1e3 --known 0.5 uci --train_edge 0.7 --data energy
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-3 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e1e3 --known 0.5 uci --train_edge 0.7 --data power
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-3 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e1e3 --known 0.5 uci --train_edge 0.7 --data kin8nm
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-3 --apply_attr --apply_peer --sample_peer_size 5  --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP3_Ablation_init_epsilon/e1e3 --known 0.5 uci --train_edge 0.7 --data naval
