# Train Edge 0.9:
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.9 --known 0.5 uci --train_edge 0.9 --data yacht
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.9 --known 0.5 uci --train_edge 0.9 --data wine
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.9 --known 0.5 uci --train_edge 0.9 --data housing
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.9 --known 0.5 uci --train_edge 0.9 --data concrete
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.9 --known 0.5 uci --train_edge 0.9 --data energy
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --very_large_dataset --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.9 --known 0.5 uci --train_edge 0.9 --data power
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --very_large_dataset --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.9 --known 0.5 uci --train_edge 0.9 --data kin8nm
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --very_large_dataset --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.9 --known 0.5 uci --train_edge 0.9 --data naval
                                                                                                                                                           
# Train Edge 0.5:                                                                                                                                          
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.5 --known 0.5 uci --train_edge 0.5 --data yacht
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.5 --known 0.5 uci --train_edge 0.5 --data wine
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.5 --known 0.5 uci --train_edge 0.5 --data housing
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.5 --known 0.5 uci --train_edge 0.5 --data concrete
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.5 --known 0.5 uci --train_edge 0.5 --data energy
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --very_large_dataset --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.5 --known 0.5 uci --train_edge 0.5 --data power
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --very_large_dataset --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.5 --known 0.5 uci --train_edge 0.5 --data kin8nm
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --very_large_dataset --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.5 --known 0.5 uci --train_edge 0.5 --data naval
                                                                                                                                                           
# Train Edge 0.3:                                                                                                                                          
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.3 --known 0.5 uci --train_edge 0.3 --data yacht
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.3 --known 0.5 uci --train_edge 0.3 --data wine
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.3 --known 0.5 uci --train_edge 0.3 --data housing
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.3 --known 0.5 uci --train_edge 0.3 --data concrete
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.3 --known 0.5 uci --train_edge 0.3 --data energy
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --very_large_dataset --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.3 --known 0.5 uci --train_edge 0.3 --data power
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --very_large_dataset --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.3 --known 0.5 uci --train_edge 0.3 --data kin8nm
python train_mdi.py --epochs 40000 --repeat_exp_num 5 --very_large_dataset --init_epsilon 1e-4 --apply_attr --apply_peer --sample_peer_size 5 --sample_strategy cos-similarity --node_dim 128 --edge_dim 128 --impute_hidden 128 --log_dir EXP2_robust/train_edge_0.3 --known 0.5 uci --train_edge 0.3 --data naval
